print("\tahoj \"Pavle\". \n Jak se máš", end="\n\n\n")
#print()
#print( 3 + 5, 4 + 8, 5 + 6, sep="----" end ="!!!")
#print("Hello, "World", sep="***", end="*")

cislo1 = int(input("Zadej prvni cislo: "))
cislo2 = input("Zadej druhe cislo: ")
cislo2 = int(cislo2)
print("Prvni cislo je:", cislo1)
print("Druhe cislo je:", cislo2)
print("Soucet je:", cislo1 + cislo2)
print("je:", cislo1 - cislo2)
print("je:", cislo1 / cislo2)
print("je:", cislo1 * cislo2)
print("je:", cislo1 / 100 * cislo2)
print("je:", cislo1 % cislo2)
print("je:", cislo1 // cislo2)
napoj = input("Co rad pijes") 
if vek >= 18:
    print ("Slvele")
    print("vitame te tu")
elif vek >= 15:
    print("Pojd dovnitr, mame tu tri druhy limonady") 
else: print("bohuyel to pro tebe nic nemame")
