# Generated by Django 4.0.3 on 2022-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zvire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('barva', models.CharField(max_length=100)),
                ('vaha', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
    ]
