# Generated by Django 4.0.3 on 2022-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informace', '0002_alter_zvire_popis_alter_zvire_vaha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvire',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zvire',
            name='vaha',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
